### ISSUE TITLE
Recent UI changen

### ISSUE THREAD

**Issue by pieters2** [Zren/ResizeYoutubePlayerToWindowSize#78] opened 2023-06-28 23:21 UTC
Youtube changed how its UI works and it is now above the video 
<img width="1753" alt="Screenshot 1" src="https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/67297010/ed0fb491-4daf-4e9b-923f-805dcf315c38">

**Comment by krystian3w** [comment] 2023-06-28 23:37
Also down these option in Enhancer for YouTube™.

**Comment by krystian3w** [comment] 2023-06-28 23:40
Duplicate of [#77](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/issues/77 "looks similar")

**Comment by Zren** [comment] 2023-06-29 04:16
Dupe. Also fixed in v132.

**Closed by Zren** 2023-06-29 04:16 UTC
