### ISSUE TITLE
YT pushed some update it seems

### ISSUE THREAD

**Issue by black-ish** [Zren/ResizeYoutubePlayerToWindowSize#79] opened 2023-08-17 14:52 UTC
Youtube seems to have updated something, while resizing still works the playlist and parts of the description is now over the video.
![2023 08 17_16：47：01_Wnj89TMe8O](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/41301048/823d350c-9839-4f5b-a863-bf4ba14f6a2b)

There is also quite a bit of black space above the video now.
![2023 08 17_16：47：10_52eL13bke4](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/41301048/34d95355-0026-459d-af9f-fa0605d398dd)

I deactiavted all other scripts to check which one it is, it seems to be this one which is why I'm posting it here, hopefully someone else can confirm it.

**Comment by Zren** [comment] 2023-08-17 16:50
Can't reproduce atm with Linux Firefox v116 or Linux Chromium v116. I'll keep checking over the next couple of days to see if I get the A/B test.

* Since you're logged out of Youtube, can you tell me which browser?
* As well as hit F12 to open the DevTools.
  * Click the Storage tab in Firefox, or Application in Chromium.
  * Click "Cookies" in the sidebar, then "youtube.com"
  * You should see a `VISITOR_INFO1_LIVE=-gmh76OPtVY` and `YSC=7VP5GD13ohM`. I think those are the cookies that control the A/B tests on Youtube.

**Comment by black-ish** [comment] 2023-08-17 17:10
This is CentBrowser, which is a Chromium based Browser.
For the VISITOR_INFO1_LIVE I get: xKhLxvsUd44
For YSC I get: aaeNIQcsp68

I'll try to check with other Browsers, it just happened today, yesterday all worked fine.

**Comment by black-ish** [comment] 2023-08-17 17:12
Ok this is interesting, with Pale Moon (XUL Based) I'm getting the same result as with CentBrowser.
With Vivaldi it seems to work still, I'm checking if there are different scripts running.

**Comment by Zren** [comment] 2023-08-17 19:26
> Ok this is interesting, with Pale Moon (XUL Based) I'm getting the same result as with CentBrowser.

The A/B test might be IP/Country based.

Using those cookies doesn't seem to work, so I'll stop asking for them in the future.

> But I got the same "black space" at the top for a bit there even on the main Youtube page, which may be something else then...

That's probably from #76 which appears when you use the back button.

**Comment by Vamael** [comment] 2023-08-18 16:34
Can confirm on Firefox 107.0.1 on Windows. Disabling min-height, height and position in <div id="player-full-bleed-container" class="style-scope ytd-watch-flexy"> seems to fix it

**Comment by AndrewTheWookiee** [comment] 2023-08-18 17:24
Having the same issues, adding the line Vamael posted fixes it.

**Comment by iPaulis** [comment] 2023-08-18 17:24
I can confirm the same problem on Firefox v116.0.3 on Windows, it was just pushed a couple of minutes ago for me, as I was watching youtube, previous tabs were just fine, and suddenly it started happening in any new one. Now if I refresh any of the previously correctly loaded tabs, they apply the new youtube changes and break.

**Comment by Zren** [comment] 2023-08-18 18:02
Quickly added @Vamael's fix. If there's any minor issues I'll fix them after lunch.

**Comment by black-ish** [comment] 2023-08-18 18:18
Updated to version 133 for a first try it seems to work fine :)
Thank you guys for confirming and giving the instructions to fix and updating the script :)

**Comment by marvtobi** [comment] 2023-08-18 18:22
Thanks zren! 133v fix works for me on current up to date Firefox and with Greasemonkey

**Comment by Zren** [comment] 2023-08-18 21:10
> There's a "scroll" that happens that doesn't get corected for though:

@tordenflesk: I can't reproduce this. Is it caused by Youtube? or another Youtube extension? It sounds similar to #58.

**Comment by tordenflesk** [comment] 2023-08-18 21:50
> > There's a "scroll" that happens that doesn't get corected for though:
> 
> @tordenflesk: I can't reproduce this. Is it caused by Youtube? or another Youtube extension? It sounds similar to #58.

Apperas to have been temporary between manually applying @vamael's fix and v133

**Comment by tordenflesk** [comment] 2023-08-22 16:24
Issue shows up again today:
![image](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/2136727/b0484bef-33de-40f7-81ed-7315ce907e58)

**Comment by Vamael** [comment] 2023-08-22 17:40
Yep, youtube changed something again. For now, manually update the script by adding `scriptSelector + ' ytd-watch-flexy[full-bleed-player] #full-bleed-container.ytd-watch-flexy',` on line ~600, just under `scriptSelector + ' ytd-watch-flexy[full-bleed-player] #player-full-bleed-container.ytd-watch-flexy',`

@Zren Can you update the script again? :)

**Comment by Tharn** [comment] 2023-08-22 17:49
Made me think there was something wrong with my GPU... thanks YouTube. :')

Actually, thank you Zren for an amazing userscript.

**Comment by Zren** [comment] 2023-08-22 19:05
Thanks again @Vamael. Looks like the CSS moved the `position: relative` to another wrapper div.

**Comment by Chris15294** [comment] 2023-08-22 19:29
I'm still experiencing the error even with the new update
![image](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/33099253/500db97e-b0a7-4091-88f4-7ad17c8c6bae)

**Comment by evkaw** [comment] 2023-08-30 12:34
YouTube broke it again, lmao

**Comment by Tharn** [comment] 2023-08-30 13:32
It did? All working as intended here, with the script update from last week.

**Comment by marcelbrode** [comment] 2023-08-30 14:56
> It did? All working as intended here, with the script update from last week.

Not for me using Chrome on Win10. The patch only helped for like a day and went back to the broken state:

![ZNyJ3w2 1](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/40024364/2b452cba-1441-49a3-9767-d6f34fca1771)

**Comment by Zren** [comment] 2023-08-30 15:09
@evkaw: Youtube broke twice this past week fixed in ResizeYT v133, then again in v134. If you are sure you are using v134, then can you do the following:


1. Open Youtube while logged out (Eg: Chrome Incognito or Firefox Private mode) to avoid any personal data that might be in the HTML.
2. Open the DevTools with `F12`
3. Click the Console tab at the top.
4. Copy the following JavaScript.
5. Click the input text field next to the `>` at the bottom:
6. Paste the script, then hit `Enter`.
7. Copy the output text
  * Firefox: Right Click text > Copy Object
  * Chrome: Select all text > Copy
8. Paste it here as a comment.


```js
ytwp.debugPage = function() {
        function prettyHtml(el) {
            var s = el.outerHTML
            return s.substr(0, s.indexOf('>')+1)
        }
        var defStyle = {
            'display':'block',
            'left': 'auto', 'right': 'auto', 'top': 'auto', 'bottom': 'auto',
            'padding-left':'0px', 'padding-right':'0px', 'padding-top':'0px', 'padding-bottom':'0px',
            'margin-left':'0px', 'margin-right':'0px', 'margin-top':'0px', 'margin-bottom':'0px',
            'width': 'auto', 'min-width': 'auto', 'max-width': 'auto',
            'height': 'auto', 'min-height': 'auto', 'max-height': 'auto',
        }
        var keyFilter = Object.keys(defStyle)
        var node = document.querySelector('#movie_player video')
        var outStr = ''
        while (node.parentNode) {
            var style = getComputedStyle(node)
            var styleDiff = {}
            for (var key of style) {
                if (keyFilter.includes(key) && style[key] != defStyle[key]) {
                    styleDiff[key] = style[key]
                }
            }
            outStr += prettyHtml(node) + ' ' + JSON.stringify(styleDiff) + '\n'
            node = node.parentNode
        }
        outStr = outStr.split('\n').reverse().join('\n')
        ytwp.log(outStr)
    }
ytwp.debugPage()
```



Eg: ![Screenshot_20230830_105242](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/416367/b6f3e1a1-4b5a-4f2b-ae37-a8508f670682)


![Screenshot_20230830_110349](https://github.com/Zren/ResizeYoutubePlayerToWindowSize/assets/416367/77eca699-180f-475b-97e7-de81ee4f25d8)



```html
<html style="font-size: 10px;font-family: Roboto, Arial, sans-serif;" lang="en-GB" dark="" system-icons="" typography="" typography-spacing="" darker-dark-theme="" darker-dark-theme-deprecate=""> {"height":"3461px","max-height":"none","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<body dir="ltr" rounded-container="" modern-dialog="" class="ytwp-window-player ytwp-scrolltop ytwp-viewing-video"> {"height":"2657.67px","margin-top":"803.333px","max-height":"none","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<ytd-app darker-dark-theme=""> {"height":"2657.67px","left":"0px","max-height":"none","max-width":"none","min-height":"100%","min-width":"0px","right":"0px","top":"0px","width":"1600px"}
<div id="content" class="style-scope ytd-app"> {"height":"2657.67px","max-height":"none","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<ytd-page-manager id="page-manager" class="style-scope ytd-app"> {"display":"flex","height":"2657.67px","margin-top":"56px","max-height":"none","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<ytd-watch-flexy class="style-scope ytd-page-manager hide-skeleton" theater-requested_="" js-panel-height_="" flexy-enable-small-window-sizing="" flexy-enable-large-window-sizing="" cinematics-enabled="" flexy="" rounded-info-panel="" is-dark-theme="" is-four-three-to-sixteen-nine-video_="" theater="" full-bleed-player="" watch-metadata-refresh="" is-two-columns_="" flexy-large-window_="" style="--ytd-watch-flexy-scrollbar-width: 0px; --ytd-watch-flexy-space-below-player: 136px; --ytd-watch-flexy-panel-max-height: 460px; --ytd-watch-flexy-chat-max-height: 460px; --ytd-watch-flexy-structured-description-max-height: 460px; --ytd-watch-flexy-comments-panel-max-height: 460px; --ytd-comments-engagement-panel-content-height: 460px;" role="main" video-id="BYRdRSon1Bo"> {"height":"2586.67px","max-height":"none","max-width":"none","min-width":"0px","padding-top":"71px","width":"1600px"}
<div id="full-bleed-container" class="style-scope ytd-watch-flexy"> {"display":"flex","height":"0px","max-height":"634.333px","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<div id="player-full-bleed-container" class="style-scope ytd-watch-flexy"> {"height":"0px","max-height":"none","max-width":"none","min-height":"0px","width":"1600px"}
<div id="player-container" role="complementary" class="style-scope ytd-watch-flexy" style="touch-action: auto;"> {"bottom":"0px","height":"803.333px","left":"0px","max-height":"803.333px","max-width":"100%","min-height":"803.333px","min-width":"100%","right":"0px","top":"0px","width":"1600px"}
<ytd-player id="ytd-player" context="WEB_PLAYER_CONTEXT_CONFIG_ID_KEVLAR_WATCH" class="style-scope ytd-watch-flexy"> {"height":"803.333px","max-height":"none","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<div id="container" class="style-scope ytd-player"> {"height":"803.333px","max-height":"none","max-width":"none","min-height":"0px","min-width":"0px","width":"1600px"}
<div class="html5-video-player ytp-transparent ytp-exp-bottom-control-flexbox ytp-exp-ppp-update ytp-hide-info-bar ytp-large-width-mode ytp-fine-scrubbing-exp ytp-fit-cover-video ytp-autonav-endscreen-cancelled-state ytp-heat-map paused-mode" tabindex="-1" id="movie_player" data-version="/s/player/16f9263d/player_ias.vflset/en_GB/base.js" aria-label="YouTube Video Player"> {"bottom":"0px","height":"803.333px","left":"0px","max-height":"803.333px","max-width":"100%","min-height":"803.333px","min-width":"100%","right":"0px","top":"0px","width":"1600px"}
<div class="html5-video-container" data-layer="0"> {"bottom":"0px","height":"803.333px","left":"0px","max-height":"803.333px","max-width":"100%","min-height":"803.333px","min-width":"100%","right":"0px","top":"0px","width":"1600px"}
<video tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" style="width: 1428px; height: 803px; left: 86px; top: 0px;" src="blob:https://www.youtube.com/ac36bcdd-eedc-4b21-b414-034fe8f23f8a"> {"bottom":"0px","height":"803.333px","left":"0px","max-height":"803.333px","max-width":"100%","min-height":"803.333px","min-width":"100%","right":"0px","top":"0px","width":"1600px"}
```

**Comment by Zren** [comment] 2023-08-30 18:37
Hmm, interesting, Since it's Youtube JP, it could be a unique layout for Japanese language, or just another A/B test with Japan as the test market. If it's an A/B test, then I'll probably see it in a few weeks.

-----

Anyways, I don't see any personal info in my HTML output, but if you're willing to run the script you can email me privately with the output.

My email is at the top of this page: https://github.com/Zren/ResizeYoutubePlayerToWindowSize/commit/b53d408d303b7396c67c1151ea29fd6e2f7fae88.patch

**Comment by Zren** [comment] 2023-08-30 18:38
Or it's a unique layout just for Youtube Shorts. Does it also affect normal videos?

**Comment by evkaw** [comment] 2023-08-30 18:40
yea, that's not a youtube short and also, I don't think its special to JP cause every account is in JP for me. Though I'll try the script

**Comment by evkaw** [comment] 2023-08-30 18:46
Don't know if I'm doing something wrong, but this is what I get as an output: 

VM3911:1 Uncaught ReferenceError: ytwp is not defined
    at <anonymous>:1:5

**Closed** 2023-10-31 17:51 UTC
